//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputJSONs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputJSONs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterfaceTests.InputJSONs", typeof(InputJSONs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			{&quot;MeasureDMMResistance&quot;:true,&quot;DMMResistance&quot;:{&quot;Voltage&quot;:30.0,&quot;Iterations&quot;:3,&quot;CorrectionPercentage&quot;:10},&quot;IV&quot;:1,&quot;SPS&quot;:0,&quot;SPSVoltagesIsOffsets&quot;:0,&quot;IVVoltages&quot;:[10.0,11.0,12.0,13.0],&quot;SPSVoltages&quot;:[8.0,9.0,10.0,11.0],&quot;Blocks&quot;:[{&quot;Modules&quot;:[{&quot;Arrays&quot;:[{&quot;Barcode&quot;:&quot;&quot;,&quot;SiPMs&quot;:[{&quot;DMMResistance&quot;:0,&quot;IV&quot;:1,&quot;SPS&quot;:1,&quot;SPSVoltagesIsOffsets&quot;:0,&quot;IVVoltages&quot;:[],&quot;SPSVoltages&quot;:[]},{&quot;DMMResistance&quot;:0,&quot;IV&quot;:1,&quot;SPS&quot;:1,&quot;SPSVoltagesIsOffsets&quot;:0,&quot;IVVoltages&quot;:[],&quot;SPSVoltages&quot;:[]},{&quot;DMMResistance&quot;:0,&quot;IV&quot;:1,&quot;SPS&quot;:1,&quot;SPSVoltagesIsOffset [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputJSON1 {
            get {
                return ResourceManager.GetString("inputJSON1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			{&quot;MeasureDMMResistance&quot;:true,&quot;DMMResistance&quot;:{&quot;Voltage&quot;:30,&quot;Iterations&quot;:5,&quot;CorrectionPercentage&quot;:10},&quot;IV&quot;:0,&quot;SPS&quot;:0,&quot;DarkCurrent&quot;:0,&quot;ForwardResistance&quot;:0,&quot;SPSVoltagesIsOffsets&quot;:0,&quot;IVVoltages&quot;:[],&quot;SPSVoltages&quot;:[],&quot;Blocks&quot;:[{&quot;Modules&quot;:[{&quot;Arrays&quot;:[{&quot;Barcode&quot;:&quot;00319&quot;,&quot;SiPMs&quot;:[{&quot;DMMResistance&quot;:0,&quot;IV&quot;:1,&quot;SPS&quot;:0,&quot;DarkCurrent&quot;:0,&quot;ForwardResistance&quot;:0,&quot;SPSVoltagesIsOffsets&quot;:0,&quot;IVVoltages&quot;:[],&quot;SPSVoltages&quot;:[],&quot;OperatingVoltage&quot;:41.54},{&quot;DMMResistance&quot;:0,&quot;IV&quot;:0,&quot;SPS&quot;:0,&quot;DarkCurrent&quot;:0,&quot;ForwardResistance&quot;:0,&quot;SPSVol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputJSON2 {
            get {
                return ResourceManager.GetString("inputJSON2", resourceCulture);
            }
        }
    }
}
